#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ======================
// 颜色输出工具
// ======================
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  blue: '\x1b[34m',
};

function log(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function success(message) {
  log(`✅ ${message}`, colors.green);
}

function warning(message) {
  log(`⚠️  ${message}`, colors.yellow);
}

function error(message) {
  log(`❌ ${message}`, colors.red);
}

function info(message) {
  log(`ℹ️  ${message}`, colors.cyan);
}

function header(message) {
  log(`\n${'='.repeat(50)}`, colors.blue);
  log(`${message}`, colors.bright + colors.blue);
  log(`${'='.repeat(50)}`, colors.blue);
}

// ======================
// 检测工具函数
// ======================
function execCommand(command) {
  try {
    return execSync(command, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
  } catch (err) {
    return null;
  }
}

function detectNode() {
  const nodePath = execCommand('which node');
  const nodeVersion = execCommand('node --version');
  
  if (nodePath && nodeVersion) {
    return { path: nodePath, version: nodeVersion };
  }
  return null;
}

function detectJava() {
  // 尝试使用 /usr/libexec/java_home
  let javaHome = execCommand('/usr/libexec/java_home 2>/dev/null');
  
  if (!javaHome) {
    // 备用方案:检查 JAVA_HOME 环境变量
    javaHome = process.env.JAVA_HOME;
  }
  
  if (javaHome && fs.existsSync(javaHome)) {
    const javaVersion = execCommand('java -version 2>&1 | head -n 1');
    return { home: javaHome, version: javaVersion || 'Unknown' };
  }
  
  return null;
}

function detectAllure() {
  const allurePath = execCommand('which allure');
  
  if (allurePath) {
    // 验证 Allure 是否可用（忽略 Java 错误）
    const allureVersion = execCommand('allure --version 2>&1 | grep -v "dyld" | grep -v "Library not loaded" | head -n 1');
    
    // 如果是 Homebrew 安装的，提供额外信息
    if (allurePath.includes('/homebrew/bin/allure')) {
      console.log('ℹ️  Detected Homebrew installation - will use libexec path to avoid wrapper issues');
    }
    
    return { path: allurePath, version: allureVersion || 'Unknown' };
  }
  
  return null;
}

// ======================
// 配置生成
// ======================
function generateEnvFile(config) {
  const projectPath = path.resolve(__dirname);
  const scriptPath = path.join(projectPath, 'allure-tool', 'allure-cli.js');
  
  const envContent = `# ==============================================
# E2E Report Tools Configuration
# ==============================================
# Auto-generated by setup.js on ${new Date().toISOString()}
# ==============================================

# Java Configuration
JAVA_HOME=${config.java.home}

# Allure Configuration
ALLURE_BIN=${config.allure.path}

# Node Configuration (for Shortcuts)
NODE_BIN=${config.node.path}

# Project Paths (for Shortcuts)
PROJECT_PATH=${projectPath}
SCRIPT_PATH=${scriptPath}
`;

  const envPath = path.join(__dirname, '.env');
  fs.writeFileSync(envPath, envContent, 'utf8');
  
  return { projectPath, scriptPath };
}

function setExecutablePermission() {
  const scriptPath = path.join(__dirname, 'allure-tool', 'allure-cli.js');
  try {
    execSync(`chmod +x "${scriptPath}"`);
    return true;
  } catch (err) {
    return false;
  }
}

// ======================
// 输出 Shortcuts 配置信息
// ======================
function printShortcutsInfo(paths) {
  header('Shortcuts Configuration');
  
  console.log('\n📋 Use these values in your macOS Shortcuts:\n');
  
  log('NODE_BIN:', colors.cyan);
  log(`  ${paths.nodePath}\n`, colors.bright);
  
  log('SCRIPT_PATH:', colors.cyan);
  log(`  ${paths.scriptPath}\n`, colors.bright);
  
  log('PROJECT_PATH:', colors.cyan);
  log(`  ${paths.projectPath}\n`, colors.bright);
  
  console.log('');
  info('See shortcuts/README.md for detailed setup instructions');
  console.log('');
}

// ======================
// 主逻辑
// ======================
function main() {
  const args = process.argv.slice(2);
  const isShortcutsInfoOnly = args.includes('--shortcuts-info');
  
  if (isShortcutsInfoOnly) {
    // 只输出 Shortcuts 配置信息
    const envPath = path.join(__dirname, '.env');
    if (!fs.existsSync(envPath)) {
      error('.env file not found! Please run "npm run setup" first.');
      process.exit(1);
    }
    
    require('dotenv').config({ path: envPath });
    
    printShortcutsInfo({
      nodePath: process.env.NODE_BIN,
      scriptPath: process.env.SCRIPT_PATH,
      projectPath: process.env.PROJECT_PATH,
    });
    
    return;
  }
  
  // 完整安装流程
  header('E2E Report Tools Setup');
  
  console.log('\n🔍 Detecting environment...\n');
  
  // 检测 Node.js
  const nodeInfo = detectNode();
  if (nodeInfo) {
    success(`Node.js: ${nodeInfo.version} (${nodeInfo.path})`);
  } else {
    error('Node.js not found!');
    console.log('   Please install Node.js: https://nodejs.org/\n');
  }
  
  // 检测 Java
  const javaInfo = detectJava();
  if (javaInfo) {
    success(`Java: ${javaInfo.version}`);
    info(`JAVA_HOME: ${javaInfo.home}`);
  } else {
    error('Java not found!');
    console.log('   Install via Homebrew: brew install openjdk@21');
    console.log('   Or download from: https://adoptium.net/\n');
  }
  
  // 检测 Allure
  const allureInfo = detectAllure();
  if (allureInfo) {
    success(`Allure: ${allureInfo.version} (${allureInfo.path})`);
  } else {
    error('Allure not found!');
    console.log('   Install via Homebrew: brew install allure\n');
  }
  
  // 检查是否所有依赖都满足
  if (!nodeInfo || !javaInfo || !allureInfo) {
    console.log('');
    warning('Some dependencies are missing. Please install them and run setup again.');
    process.exit(1);
  }
  
  // 生成 .env 文件
  console.log('');
  info('Generating .env file...');
  
  const config = {
    node: nodeInfo,
    java: javaInfo,
    allure: allureInfo,
  };
  
  const paths = generateEnvFile(config);
  success('.env file created!');
  
  // 设置执行权限
  if (setExecutablePermission()) {
    success('Set executable permission for allure-cli.js');
  }
  
  // 输出 Shortcuts 配置信息
  printShortcutsInfo({
    nodePath: nodeInfo.path,
    scriptPath: paths.scriptPath,
    projectPath: paths.projectPath,
  });
  
  // 下一步提示
  header('Next Steps');
  console.log('');
  log('1. Configure macOS Shortcuts:', colors.cyan);
  console.log('   Run: npm run install-shortcuts');
  console.log('   Or manually follow: shortcuts/README.md\n');
  
  log('2. Test the setup:', colors.cyan);
  console.log('   In Finder, right-click a test result file');
  console.log('   Select: Quick Actions → Generate Allure Report\n');
  
  success('Setup completed! 🎉');
  console.log('');
}

// ======================
// 入口
// ======================
main();
